implement button class
ICS4U-Gallo/class-rpg-game pull request #4
Opened 2021-11-19 19:54 UTC by harry7557558

Implement a button class.

The button class has an `__init__` function, a `draw` function, a `mouse_move` function and a `mouse_click` function to be called manually when the mouse moved or button-down. It supports different appearances when the mouse hovers or is clicked. It also allows adding a list of functions to be called when the mouse is clicked, which can be accessed using the `onclicks` object or the `add_onclick` instance.

2021-11-29 18:51 UTC, MrGallo requested changes

2021-11-29 18:51 UTC, MrGallo commented on rpg/button.py
> +    onclicks: List[Callable]
Delete these.

2021-11-29 18:51 UTC, MrGallo commented on rpg/button.py
> +                 image_click=None):
Make `image_default` a required argument. Remove the `w` and `h` and derive them.

2021-11-29 18:51 UTC, MrGallo commented on rpg/button.py
> +        if 0 <= mouse_x-self.pos_x < self.width and 0 <= mouse_y-self.pos_y < self.height:
Suggestion: 
```python
return self.rect.collidepoint((mouse_x, mouse_y))
```

2021-11-29 18:51 UTC, MrGallo commented on rpg/button.py
> +        self.onclicks = []
Suggestion: Add `self.rect = pygame.Rect(x, y, w, h)`.

2021-12-01 19:33 UTC, harry7557558 commented
I updated the constructor of the `Button` class. I made `image_default` a required argument, which can be a path to the image file, a `pygame.Surface`, or an RGB color. I keep `width` and `height` as optional arguments because they are needed when `image_default` is a color.

2023-10-07 22:48 UTC, closed without merging